[workspace]
members = [
    "engine",
    "engine/vault",
    "engine/primitives",
    "engine/random",
    "engine/crypto",
    "engine/snapshot",
    "stronghold",
]
exclude = [
  "engine/examples/commandline",
]
