[workspace]
members = [
    "parti",
    "parti/vault",
    "parti/primitives",
    "parti/random",
    "parti/crypto",
    "parti/snapshot",
    "stronghold",
]
exclude = [
  "parti/examples/commandline",
]
