apiVersion: v1
kind: Namespace
metadata:
  name: parti
spec:
  selector:
    matchLabels:
      name: parti
  template:
    metadata:
      labels:
        name: parti
    spec:
      containers:
        - name: parti-fuzz
          image: tensorprogramming/parti
          imagePullPolicy: IfNotPresent
