[package]
name = "stronghold"
version = "0.1.0"
authors = ["Marcelo R. Bianchi <marcelo.bianchi@iota.org>"]
edition = "2018"

[dependencies]
bee-ternary = { git = "https://github.com/iotaledger/bee", features = ["serde1"] }

#parti
vault = {path = "../parti/vault"}
crypto = {path = "../parti/crypto"}
random = {path = "../parti/random"}
snapshot = {path = "../parti/snapshot"}
primitives = {path = "../parti/primitives"}
bincode = "1.3.1"
serde = {version = "1.0.114", features = ["derive"]}