name: Build and run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        project: [parti, stronghold]
        rust: [nightly, beta, stable]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install ${{ matrix.rust }} toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Get current date
      run: ::set-env name=CURRENT_DATE::$(date +'%Y-%m-%d')

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache cargo target
      uses: actions/cache@v2
      with:
        path: ${{ matrix.project}}/target
        # Add date to the cache to keep it up to date (for example, new nightly toolchain update may change build cache)
        key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}-$CURRENT_DATE
        # Restore from outdated cache for speed
        restore-keys: |
          ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}

    - name: Build ${{ matrix.project }}
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=${{ matrix.project }}/Cargo.toml --all --release

    - name: Run tests for ${{ matrix.project }}
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=${{ matrix.project }}/Cargo.toml --all --release
