name: Release Stronghold CLI

on:
  workflow_dispatch:
  push:
    branches:
      - ci/cli-release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: engine/examples/commandline

    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # - name: Get current date
    #   if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
    #   run: echo "::set-env name=CURRENT_DATE::$(date +'%Y-%m-%d')"

    # - name: Get current date
    #   if: matrix.os == 'windows-latest'
    #   run: echo "::set-env name=CURRENT_DATE::$(Get-Date -Format "yyyy-MM-dd")"

    # - name: Cache cargo registry
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cargo/registry
    #     # Add date to the cache to keep it up to date
    #     key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
    #     # Restore from outdated cache for speed
    #     restore-keys: |
    #       ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

    # - name: Cache cargo index
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cargo/git
    #     # Add date to the cache to keep it up to date
    #     key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
    #     # Restore from outdated cache for speed
    #     restore-keys: |
    #       ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}

    # - name: Cache cargo target
    #   uses: actions/cache@v2
    #   with:
    #     path: ${{ matrix.project}}/target
    #     # Add date to the cache to keep it up to date
    #     key: ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
    #     # Restore from outdated cache for speed
    #     restore-keys: |
    #       ${{ matrix.project }}-${{ matrix.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}

    - name: Build Stronghold CLI
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=engine/examples/commandline/Cargo.toml --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: stronghold-cli-${{ matrix.os }}
        path: |
          engine/examples/commandline/target/release/stronghold
          engine/examples/commandline/target/release/stronghold.exe
